services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501" 
    volumes:
      - .:/app
      - ./models:/app/models  # New volume for LLM models
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_network

volumes:
  qdrant_data:

networks:
  app_network:
    driver: bridge