services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501" 
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=ollama
      - QDRANT_HOST=qdrant
    depends_on:
      - ollama
      - qdrant
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    pull_policy: if_not_present
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - app_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app_network

volumes:
  qdrant_data:

networks:
  app_network:
    driver: bridge