qdrant:
  # Use the service name as defined in docker-compose
  url: "http://qdrant:6333"
  collection_name: "cancer"
  vector_size: 384
  distance_metric: "Cosine"
  dense_model: "sentence-transformers/all-MiniLM-L6-v2"
  sparse_model: "prithivida/Splade_PP_en_v1"

wikipedia_api:
  base_url: "https://en.wikipedia.org/w/api.php"

api:
  generate_url : "http://app:8000/generate"
  ingest_url : "http://app:8000/ingest"

logging:
  log_file: "app.log"
  log_level: "INFO"

llm:
  model_name: "llama3.2"
  temperature: 0.1
  max_tokens: 512
  api_url: "http://ollama:11434/api/generate"
  system_prompt: |
    Context is below.
    -------------------------
    {context}
    -------------------------
    Given the context information and not prior knowledge, answer the query asking about the question related to cancer. Please provide your answer in a way like a specialist cancer doctor would reply. Strictly use the context for answering the user query.
    Query: {query}
    Answer:



search:
  default_limit: 5
  score_threshold: 0.5