qdrant:
  # Use the service name as defined in docker-compose
  url: "http://qdrant:6333"
  collection_name: "cancer"
  vector_size: 384
  distance_metric: "Cosine"
  dense_model: "sentence-transformers/all-MiniLM-L6-v2"
  sparse_model: "prithivida/Splade_PP_en_v1"

wikipedia_api:
  base_url: "https://en.wikipedia.org/w/api.php"

# Update to use the service name instead of localhost
fast_api_url: "http://app:8000/api/generate"

logging:
  log_file: "app.log"
  log_level: "INFO"

llm:
  model_name: "llama3.2"
  temperature: 0.1
  max_tokens: 512
  # Use the service name and correct port
  api_url: "http://ollama:11434/api/generate"
  system_prompt: ""

search:
  default_limit: 5
  score_threshold: 0.5