qdrant:
  url : "http://localhost:6333"
  collection_name: "cancer"
  vector_size: 384
  distance_metric: "Cosine"
  dense_model: "sentence-transformers/all-MiniLM-L6-v2"
  sparse_model : "prithivida/Splade_PP_en_v1"

wikipedia_api:
  base_url: "https://en.wikipedia.org/w/api.php"
  

logging:
  log_file: "app.log"
  log_level: "INFO"

llm:
  model_name: "llama3.2"
  temperature: 0.1
  max_tokens: 512
  api_url: "http://localhost:11434/api/generate"
  system_prompt: ""

search:
  default_limit: 5
  score_threshold: 0.5

